kaspanet/rusty-kaspa

Cargo.toml, consensus/Cargo.toml, core/Cargo.toml, crypto/hashes/Cargo.toml, crypto/hashes/src/hashers.rs, crypto/hashes/src/lib.rs, crypto/hashes/src/pow_hashers.rs, crypto/muhash/Cargo.toml, crypto/muhash/benches/bench.rs, crypto/muhash/fuzz/.gitignore, crypto/muhash/fuzz/Cargo.toml, crypto/muhash/fuzz/fuzz.sh, crypto/muhash/fuzz/fuzz_targets/u3072.rs, crypto/muhash/fuzz/rust-toolchain.toml, crypto/muhash/src/lib.rs, crypto/muhash/src/u3072.rs, kaspad/Cargo.toml, wallet/Cargo.toml, wasm/Cargo.toml
A pure rust MuHash implementation of the logic in: https://github.com/kaspanet/go-muhash
I ran the fuzzer for 1.5 weeks and nothing has crashed yet.
Still trying to figure out the best way to store the fuzzing corpuses (as there are ~20k of those), probably a dedicated repository.
Note: The tests might fail for 32bit machines right now, but the logic itself should work just fine (we can decide if 32 bit machines should receive the same attention or not later)
Note2: Currently this is faster than the go+C version for everything except `Finalize()` which will get much faster by adding a `U3072` type and implementing an extended euclidean algorithm in order to invert the element
=> Implement MuHash

consensus/core/src/block.rs, consensus/core/src/header.rs, consensus/src/consensus/mod.rs, consensus/src/consensus/test_consensus.rs, consensus/src/pipeline/body_processor/body_validation_in_context.rs, consensus/src/pipeline/body_processor/body_validation_in_isolation.rs, consensus/src/pipeline/deps_manager.rs, consensus/src/pipeline/header_processor/processor.rs, consensus/tests/integration_tests.rs, consensus/tests/pipeline_tests.rs, kaspad/src/emulator.rs
Created a `MutableBlock` struct which test consensus returns from build methods, and changed `Block` to have header through an Arc, making it immutable and easy to pass by cloning (w/o another Arc around). This also saves from a full header clone on header processor commit
=> Refactor block struct

consensus/core/src/lib.rs, consensus/src/model/stores/acceptance_data.rs, consensus/src/model/stores/block_transactions.rs, consensus/src/model/stores/block_window_cache.rs, consensus/src/model/stores/daa.rs, consensus/src/model/stores/database/access.rs, consensus/src/model/stores/database/cache.rs, consensus/src/model/stores/database/item.rs, consensus/src/model/stores/depth.rs, consensus/src/model/stores/ghostdag.rs, consensus/src/model/stores/headers.rs, consensus/src/model/stores/past_pruning_points.rs, consensus/src/model/stores/reachability.rs, consensus/src/model/stores/relations.rs, consensus/src/model/stores/statuses.rs, consensus/src/model/stores/tips.rs, consensus/src/model/stores/utxo_diffs.rs, consensus/src/model/stores/utxo_multisets.rs, consensus/src/model/stores/utxo_set.rs, consensus/src/pipeline/deps_manager.rs, consensus/src/pipeline/virtual_processor/utxo_validation.rs, consensus/src/processes/ghostdag/mergeset.rs, consensus/src/processes/ghostdag/protocol.rs, consensus/src/processes/parents_builder.rs, consensus/src/processes/reachability/reindex.rs, consensus/src/processes/reachability/tests.rs, crypto/hashes/src/lib.rs
The BlockHash contains the PoW nonce, which means that trying to DOS the hashmap costs you in PoW so the PoW function actually behaves as DOS resistancy for HashMaps where the BlockHash is the key.
meaning that we don't need to pass it through `SipHash` instead we can just take the first/last 64 bits of the hash and use those as the hash for the hashmap.
=> Override Hasher on BlockHashMap and BlockHashSet

consensus/src/pipeline/header_processor/pre_ghostdag_validation.rs, kaspad/src/emulator.rs, kaspad/src/main.rs
Changes:
1) [Bug fix] - use `max_block_time` in check `check_block_timestamp_in_isolation`
2) [update emulator] -  use system time in `block.header.timestamp` and remove usage of the delay, in order to make emulator compatible with new validation logic
=> Update emulator to use systemtime, and bug fix for `check_block_timestamp_in_isolation` 

consensus/src/model/services/reachability.rs, consensus/src/processes/parents_builder.rs, consensus/src/processes/reachability/mod.rs
Improves performance drastically (avoiding a quadratic `O(num_parents^2)` term)
=> Optimize multi-level parents builder

consensus/src/model/stores/database/item.rs
Apparently the first read-lock is not released sine if-else-if are considered the same scope (?)
=> Fix a deadlock when cached item is not in cache

consensus/src/consensus/mod.rs, consensus/src/consensus/test_consensus.rs, consensus/src/model/services/statuses.rs, consensus/src/pipeline/header_processor/post_pow_validation.rs, consensus/src/pipeline/header_processor/processor.rs, consensus/src/pipeline/virtual_processor/processor.rs, consensus/src/processes/block_depth.rs, consensus/src/processes/ghostdag/protocol.rs, consensus/src/processes/pruning.rs, consensus/src/processes/reachability/mod.rs, simpa/src/main.rs, simpa/src/simulator/network.rs
Implements virtual parent selection algorithms which enforce the following mining rules:
1. Max number of direct parents
2. Mergeset size limit 
3. Bounded merge depth 
The following components of virtual processing are yet to be implemented:
- Search for alternative virtual selected parent if the current one turns out to be disqualified from chain or violates finality.
- Refactor all functions and algorithms to proper files/structs/methods
=> Virtual processor part 2 -- virtual parents selection rules

Cargo.lock, crypto/muhash/benches/bench.rs, crypto/muhash/src/u3072.rs, math/Cargo.toml, math/fuzz/fuzz_targets/u128.rs, math/fuzz/fuzz_targets/u192.rs, math/fuzz/fuzz_targets/u256.rs, math/src/uint.rs
This uses the new https://github.com/mhogrefe/malachite crate for computing modular inverses, in the future, we'd want to replace that with our own implementation of Lehmer's algorithm.
Benchmark before on my machine with turbo-boost off:
```
Uint3072/mod_inv Muhash prime
time:   [254.88 ms 257.58 ms 260.49 ms]
change: [+0.5522% +1.8513% +3.4027%] (p = 0.01 < 0.05)
Change within noise threshold.
```
After: 
```
Uint3072/mod_inv Muhash prime
time:   [1.5437 ms 1.5536 ms 1.5654 ms]
change: [-99.404% -99.396% -99.388%] (p = 0.00 < 0.05)
Performance has improved.
Found 13 outliers among 100 measurements (13.00%)
```
I will let the fuzzers run throughout the weekend
(Thanks @michaelsutton For pointing this library out and suggesting we'll use it here)
=> Use malachite for modular inverse

README.md
Clang toolchain must be installed, so I've added an entry onto the "Getting started" section.
=> Updated README.md regarding installation of clang toolchain

crypto/muhash/src/u3072.rs, math/src/uint.rs
The tests anyway don't pass for the 32 bits right now even though the code is correct.
`Uint` is using u64's and because we use that for the modular inverse they need to either have the same kind of limbs, or be converted, so for now I made MuHash always use 64bit limbs, at the cost of a performance penalty for 32 bit machines. but at least it'll compile and work properly.
The `math` crate seems to build now under wasm (`cargo b --target wasm32-unknown-unknown`)
=>  Make Muhash always use 64 bits limbs

math/fuzz/Cargo.toml, math/fuzz/fuzz_targets/u128.rs, math/fuzz/fuzz_targets/u192.rs, math/fuzz/fuzz_targets/u256.rs, math/src/uint.rs
This uses the algorithm from https://blog.m-ou.se/floats/ to convert any Uint* struct into an `f64` according to the IEEE754 spec (rounding to the closest f64).
Also used rust-bitcoin's code as another reference: https://github.com/rust-bitcoin/rust-bitcoin/blob/e83a2d34222a36d7c7c3c572f6fc8ba20b380178/bitcoin/src/pow.rs#L650
Note that I did deviate a bit from the algorithm by keeping the highest dropped bit as bool and ORing together the rest of the dropped bits into a u64 and not squashing them together into a single u64 as that is quite harder with more limbs.
But it seems that this approach might even be faster somehow?(https://godbolt.org/z/W1hvs5jKv) I'll need to write a benchmark to be sure.
I'm currently running the fuzzer on `u128` in my laptop
=> math: Add as_f64 function to Uint*

Cargo.lock, Cargo.toml, consensus/core/src/api/mod.rs, consensus/src/consensus/mod.rs, protocol/p2p/Cargo.toml, rpc/core/Cargo.toml, rpc/core/src/model/message.rs, rpc/core/src/model/peer.rs, rpc/grpc/core/src/convert/address.rs, rpc/grpc/core/src/convert/message.rs, rpc/grpc/core/src/convert/mod.rs, rpc/grpc/core/src/convert/peer.rs, rpc/service/src/converter/consensus.rs, rpc/service/src/service.rs
Enable all RPC API methods in the gRPC server.
For some methods, the response is a "Not implemented" error if `kaspa-rpc-core` has no implementation yet but both the gRPC server and the `kaspa-rpc-core` service do support all request types.
=> gRPC server complement

.github/workflows/ci.yaml, .github/workflows/deploy.yaml, Cargo.toml
In the downloadable Linux bundle, remove the dependencies of the executables to the libraries `libstdc++`, `libgcc_s` and `librt` by statically linking those.
=> Deploy Linux executables with some statically linked libraries

consensus/core/src/config/params.rs, consensus/core/src/networktype.rs, crypto/txscript/src/lib.rs, kaspad/src/main.rs, mining/src/manager_tests.rs, mining/src/mempool/check_transaction_standard.rs
Add iterating over the network parameters of all available network types.
Address some remaining TODOs asking Mempool to make use of txscript.
Add txscript `is_unspendable` function.
=> Mempool & txscript

Cargo.lock, components/connectionmanager/src/lib.rs, consensus/core/src/config/mod.rs, consensus/core/src/errors/config.rs, consensus/core/src/errors/mod.rs, kaspad/Cargo.toml, kaspad/src/args.rs, kaspad/src/main.rs, protocol/flows/src/flow_context.rs, protocol/flows/src/service.rs, protocol/p2p/src/bin/server.rs, protocol/p2p/src/core/adaptor.rs, protocol/p2p/src/core/connection_handler.rs, protocol/p2p/src/echo.rs, rpc/core/src/model/peer.rs, rpc/grpc/server/src/lib.rs, utils/src/networking.rs
Enhance `kaspad` CLI with following repeatable arguments:
- `--connect=` and `--addpeer=` for peers management.
- `--uacomment=` for user-agent comments describing the launched node (see [BIP-014](https://en.bitcoin.it/wiki/BIP_0014) for more information)
=> CLI Peers Management

crypto/txscript/src/lib.rs, crypto/txscript/src/opcodes/macros.rs, crypto/txscript/src/opcodes/mod.rs
Fixes toward https://github.com/kaspanet/rusty-kaspa/issues/122
1. Opcode serialization now include the code
2. Opcode deserialization parse code and data (`deserialize_next_opcode` renamed to `deserialize_next_opcode`, which now deseriarilze (and consumes) a whole opcode from an iterator)
3. Added tests for push data, push number and unary number opcodes
=> Ser-de opcode fixes (better api) and some opcode tests

consensus/src/consensus/mod.rs, consensus/src/consensus/storage.rs, consensus/src/constants/mod.rs, consensus/src/model/stores/ghostdag.rs, consensus/src/model/stores/headers.rs, consensus/src/model/stores/mod.rs, consensus/src/model/stores/pruning.rs, consensus/src/model/stores/pruning_utxoset.rs, consensus/src/model/stores/virtual_state.rs, consensus/src/pipeline/pruning_processor/processor.rs, consensus/src/pipeline/virtual_processor/processor.rs, consensus/src/processes/pruning_proof/mod.rs, database/src/errors.rs, mining/src/block_template/builder.rs, mining/src/mempool/model/transactions_pool.rs, mining/src/testutils/consensus_mock.rs, protocol/flows/src/v5/ibd/flow.rs, testing/integration/src/integration_tests.rs, utils/src/sync/rwlock.rs, utils/src/sync/semaphore.rs
Adds support for batching and recovery for pruning operations in order to ensure coherent state also on system crashes. 
Namely:
1. Performs pruning point utxo-set update in DB batches which include the current position
2. Uses the above position to recover the process on system restart
3. Saves the last data pruned point in the DB
4. Uses this point to trigger data prune on system restart if a former operation was uncompleted
5. This point also marks the beginning of full history for archival nodes
=> Handle recovery of pruning workflows on process crashes

components/connectionmanager/src/lib.rs, components/consensusmanager/src/lib.rs, consensus/notify/src/service.rs, consensus/src/consensus/factory.rs, consensus/src/consensus/mod.rs, consensus/src/consensus/test_consensus.rs, consensus/src/pipeline/body_processor/processor.rs, consensus/src/pipeline/virtual_processor/processor.rs, indexes/processor/src/processor.rs, indexes/processor/src/service.rs, notify/src/broadcaster.rs, notify/src/collector.rs, notify/src/notifier.rs, notify/src/root.rs, notify/src/subscriber.rs, protocol/flows/src/flow_context.rs, protocol/flows/src/service.rs, protocol/flows/src/v5/blockrelay/flow.rs, protocol/p2p/src/core/connection_handler.rs, protocol/p2p/src/handshake.rs, rpc/grpc/client/src/lib.rs, rpc/grpc/server/src/connection_handler.rs, rpc/service/src/service.rs, rpc/wrpc/client/src/client.rs, rpc/wrpc/server/src/connection.rs, rpc/wrpc/server/src/server.rs, testing/integration/src/integration_tests.rs
Implements a controlled shutdown sequence of the notification system, starting from the notification root (consensus) and up through the various index and rpc services. 
Fixes P2P cyclic reference clean up, 
Inspired and applies lessons learned from #197 by @D-Stacks. Adapts Connection Manager shutdown from @someone235's daemon branch.    
Closes #131 #132.
=> Graceful shutdown sequence

protocol/flows/src/flow_context.rs, protocol/flows/src/flow_trait.rs, protocol/flows/src/v5/address.rs, protocol/flows/src/v5/blockrelay/flow.rs, protocol/flows/src/v5/blockrelay/handle_requests.rs, protocol/flows/src/v5/ibd/flow.rs, protocol/flows/src/v5/mod.rs, protocol/flows/src/v5/ping.rs, protocol/flows/src/v5/request_anticone.rs, protocol/flows/src/v5/request_block_locator.rs, protocol/flows/src/v5/request_headers.rs, protocol/flows/src/v5/request_ibd_blocks.rs, protocol/flows/src/v5/request_ibd_chain_block_locator.rs, protocol/flows/src/v5/request_pp_proof.rs, protocol/flows/src/v5/request_pruning_point_and_anticone.rs, protocol/flows/src/v5/request_pruning_point_utxo_set.rs, protocol/flows/src/v5/txrelay/flow.rs, protocol/p2p/src/common.rs, protocol/p2p/src/core/connection_handler.rs, protocol/p2p/src/core/hub.rs, protocol/p2p/src/core/router.rs, utils/src/any.rs, utils/src/lib.rs
Sends an explicit reject message on P2P protocol errors for notifying the peer about the disconnect reason and for easier tracing of logical bugs causing protocol errors.
=> Add P2P reject message support 

consensus/src/model/stores/relations.rs, consensus/src/pipeline/pruning_processor/processor.rs, consensus/src/pipeline/virtual_processor/processor.rs, consensus/src/processes/block_depth.rs, consensus/src/processes/pruning_proof/mod.rs, consensus/src/processes/reachability/inquirer.rs, consensus/src/processes/reachability/tests/mod.rs, consensus/src/processes/relations.rs, database/src/lib.rs, database/src/writer.rs
Fixes a pruning-processor bug which can be easily reproduced with zero-cache sizes but is extremally rare if cache sizes are normal (though nonetheless can happen with some probability).
The bug is fixed by using a staging relations store for the delete operation. Required slightly refactoring the current `StagingRelationsStore` in order to fit all use cases
=> Fixes a bug with deleting level relations during pruning 

notify/src/notifier.rs, rpc/grpc/core/src/convert/message.rs, rpc/wrpc/server/src/router.rs, rpc/wrpc/server/src/server.rs
- Fixes wRPC server direct subscriptions to notifications from the hosting node
- Fixes the gRPC client so that it handles the golang version of the network type in the response to `GetCurrentNetwork`
=> Fixes 2 RPC bugs

Cargo.lock, core/Cargo.toml
this feature is used in `./tasks/ticker` but isn't specified in  theCargo.toml.
=> add tokio time feature to kaspa-core cargo.toml

Cargo.lock, Cargo.toml, components/addressmanager/Cargo.toml, components/addressmanager/src/lib.rs, consensus/core/Cargo.toml, consensus/core/src/config/mod.rs, kaspad/src/args.rs, kaspad/src/main.rs, protocol/flows/src/flow_context.rs, utils/Cargo.toml, utils/src/networking.rs
- If we can add local addresses, this assumes the first one is always the best
- If `--listen` is passed, it is added as the local address, if it's routable
- Adds the `externalip` flag
- If an external IP is passed, it is assumed to be the best one to use
- The value is added as a local address, if it's routable
- Passes the "best local IP address" to the version message
- If neither `--listen` nor `--externalip` is passed (most common default), then all interfaces are checked for local addresses that are routable and adds them to the list
=> Add base implementation of local address management

Cargo.lock, Cargo.toml
Bumps rocksdb crate version to 0.21. As a result this upgrades the underlying cpp lib to version 8.1.1, which includes a new write amplification [optimization ](https://rocksdb.org/blog/2022/10/31/align-compaction-output-file.html#:~:text=By%20cutting%20the%20compaction%20output,upgrades%20RocksDB%20to%20version%207.8). 
This should reduce some of the disk write magnitude observed in the latest testnet11 run (several TB of IO despite using only ~70GB of disk space).
Missing:
- This PR might benefit from further exploration of the various rocksdb settings related to file sizes
=> Bump rocksdb version to 0.21

Cargo.lock, components/addressmanager/Cargo.toml, components/addressmanager/src/lib.rs, core/Cargo.toml, utils/src/networking.rs
This pr weights the prefix bytes in the address manager for the `iterate_prioritized_random_addresses` method. which should more evenly spread-out the network topology as well as increasing Sybil resistance. 
The improved selection will adjust weights by dividing the weights by the size of the prefix bucket the ip belongs to. this ensures other weighting metrics are still respected, but keep a priority of selecting evenly over all prefix bytes.
=> Weight ip prefix

utils/src/networking.rs
- Return false for broadcast IPs
- Use available stable helper functions for routability check
`is_global` was considered as mentioned in https://github.com/kaspanet/rusty-kaspa/pull/222#issuecomment-1637683002 but that method is currently marked as `unstabled` and can't be used yet.
=> Refactor routability logic and handle broadcast ip

indexes/processor/src/service.rs, notify/src/broadcaster.rs, notify/src/connection.rs, notify/src/notifier.rs, rpc/grpc/server/src/connection_handler.rs, rpc/service/src/service.rs, rpc/wrpc/server/src/server.rs, wallet/core/src/wallet.rs
This small PR covers a special use case required by the wRPC client where the listeners to the wRPC client do manage the life-cycle of their notification channel so need that the notification system do not close said channel.
=> Support a persistent channel connection in the notification system

components/consensusmanager/src/session.rs, consensus/core/src/api/mod.rs, consensus/core/src/lib.rs, consensus/src/consensus/mod.rs, consensus/src/consensus/test_consensus.rs, consensus/src/model/stores/selected_chain.rs, consensus/src/pipeline/header_processor/processor.rs, consensus/src/pipeline/virtual_processor/mod.rs, consensus/src/pipeline/virtual_processor/processor.rs, consensus/src/pipeline/virtual_processor/test_block_builder.rs, consensus/src/processes/sync/mod.rs, kaspad/src/main.rs, protocol/flows/src/flow_context.rs, protocol/flows/src/v5/blockrelay/flow.rs, protocol/flows/src/v5/ibd/flow.rs, protocol/flows/src/v5/ibd/negotiate.rs, protocol/flows/src/v5/request_ibd_chain_block_locator.rs, rpc/service/src/service.rs, testing/integration/src/integration_tests.rs
This PR mainly refactors the consensus database by making the indexed selected chain store represent the *virtual* selected chain rather than the *headers* selected chain. 
Background:
- The indexed chain store indexes the selected chain with an integer index (supporting random access by index) so that it can be sampled efficiently in a logarithmic number of steps. This index is used by IBD syncing peers to sample the syncer chain and find the chain segment they are missing in ~log^2 communication rounds.
- For historic reasons the indexed chain used to represent the *headers* selected chain. Meaning it included blocks which might have not been body/utxo-processed yet. This is wrong in the context of IBD since a syncer should wish to share only fully-processed blocks
- Specifically, with …
=> IBD: fix some syncer-syncee miscommunications which are more apparent with 10 bps 

Cargo.lock, consensus/core/Cargo.toml, consensus/core/src/tx.rs, crypto/hashes/src/lib.rs
This PR implements ScriptPubKey serialization/deserialization for JSON.
=> ScriptPubKey human-readable ser/deser (for json)

kaspad/src/main.rs, simpa/src/main.rs
currently perf_monitor doesn't consider cli flag and runs always. this pr fixes the behaviour
Updated the use of .then_some with .then in simpa/src/main.rs and kaspad/src/main.rs.
=> Replace .then_some with .then in simpa and kaspad

Cargo.lock, Cargo.toml, README.md, kaspad/Cargo.toml, kaspad/src/main.rs, simpa/Cargo.toml, simpa/src/main.rs
=> Heap profiling

rpc/grpc/client/src/error.rs, rpc/grpc/client/src/lib.rs, rpc/grpc/server/src/connection.rs, rpc/grpc/server/src/connection_handler.rs, rpc/grpc/server/src/manager.rs
Fix a deadlock bug in the gRPC server occurring in case of duplicate connections with the same identity, hence same client network address.
=> Fix a gRPC server deadlock bug caused by duplicate connections

consensus/src/processes/pruning.rs, kaspad/src/daemon.rs, kaspad/src/main.rs
Return the dhat heap ALLOC profiler which was accidentally dropped when refactoring kaspad main to a daemon
=> Resurrect the heap profiler

cli/src/modules/message.rs, cli/src/modules/mod.rs
New CLI command: `message`
Subcommands:
- sign <kaspa_address> - Sign a message with the private key that matches the given address. Prompts for message.
- verify <kaspa_address> <signature> - Verify the signature against the message and kaspa_address. Prompts for message.
=> Add cli command for message sign/verify

.github/workflows/ci.yaml
Updated commands for installing gcc-multilib in ci.yaml to ensure fresh package lists are obtained before installation by invoking apt-get update first. This will prevent issues if older versions of gcc-multilib are cached, enhancing reliability of CI builds.
=> Fix gcc-multilib installation in ci.yaml

components/consensusmanager/src/session.rs, consensus/core/src/api/mod.rs, consensus/src/consensus/mod.rs, consensus/src/consensus/test_consensus.rs, consensus/src/pipeline/body_processor/body_validation_in_context.rs, consensus/src/pipeline/body_processor/body_validation_in_isolation.rs, consensus/src/pipeline/body_processor/processor.rs, consensus/src/pipeline/deps_manager.rs, consensus/src/pipeline/header_processor/processor.rs, consensus/src/pipeline/virtual_processor/processor.rs, consensus/src/pipeline/virtual_processor/tests.rs, mining/src/manager.rs, protocol/flows/src/flow_context.rs, protocol/flows/src/flowcontext/orphans.rs, protocol/flows/src/flowcontext/transactions.rs, protocol/flows/src/v5/blockrelay/flow.rs, protocol/flows/src/v5/ibd/flow.rs, protocol/flows/src/v5/txrelay/flow.rs, protocol/p2p/src/core/hub.rs, simpa/src/main.rs, simpa/src/simulator/miner.rs, testing/integration/src/consensus_integration_tests.rs, testing/integration/src/consensus_pipeline_tests.rs
Changes:
1. Refactor validate_and_insert_block to return two futures - Added in [b134d61](https://github.com/kaspanet/rusty-kaspa/pull/295/commits/b134d6128b0fe11803db77dc42218e3393804460)
- one future resolves when body processor is complete
- the other future resolves when virtual state processor is complete
The second future is used by all original callers, making the current implementation behave the same as before.
2. Change BodyProcessorMessage to VirtualStateProcessorMessage when passing the block from body-processor to virtual-processor - Added in [af066c5](https://github.com/kaspanet/rusty-kaspa/pull/295/commits/af066c50ca4e65688e19cb7be9ec797a156e286e)
3. Add conditions/checks to see if we can broadcast
4. Actually broadcast the block after Body Processor
=> Optimize P2P block processing latency -- Broadcast blocks after Body Processor

Cargo.lock, components/addressmanager/Cargo.toml, components/addressmanager/src/lib.rs, components/addressmanager/src/port_mapping_extender.rs
reorder fetching sources for external ip according to: 
external ip -> provided local address -> net interfaces -> upnp
The 'addressmanager' component of the codebase has been thoroughly refined for improved readability and maintainability. Firstly, the logic for assigning local network addresses has been streamlined and broken down into smaller methods for more clarity. Old methods 'add_routable_addresses_from_net_interfaces' and 'configured_address' have been replaced by 'routable_addresses_from_net_interfaces', 'local_addresses', and 'upnp'. This also led to the removal of redundant code.
=> Refactor 'addressmanager', reorder fetching sources for-external ip

consensus/wasm/src/keypair.rs, wallet/core/src/message.rs, wallet/core/src/wasm/message.rs, wallet/core/src/wasm/mod.rs, wasm/nodejs/message_signing.js
New JS functions:
- `signMessage(message, privkey)` - privkey can be a hex string or `PrivateKey` object
- `verifyMessage(message, signature, pubkey)` - pubkey can be a hex string or `PublicKey` object
=> Implement Message Signing WASM

Cargo.lock, Cargo.toml, cli/src/modules/wallet.rs, wallet/core/Cargo.toml, wallet/core/src/storage/local/interface.rs
- Update workflow-rs to 0.8.1 which contains
- A fix for clipboard paste while prompting for user input (paste mnemonic during import in KOS)
- Updates to the latest crate dependency versions to match rusty-kaspa
- Fix for the wallet file name generation using slugs
=> Update WRS to 0.8.1, fix wallet file naming

.github/workflows/ci.yaml, Cargo.lock, rpc/core/src/api/Extending RpcApi.md, test, testing/integration/Cargo.toml, testing/integration/src/common/mod.rs, testing/integration/src/common/utils.rs, testing/integration/src/lib.rs, testing/integration/src/mempool_benchmarks.rs, testing/integration/src/rpc_tests.rs
Test currently covers all RPC calls, but those that are failing or those that are unimplemented are commented out
To execute this test, run:
```
cargo test --release --package kaspa-testing-integration --lib --features devnet-prealloc -- rpc_tests::base_test --exact --nocapture --ignored
```
=> Create RPC Integration Tests

components/addressmanager/src/lib.rs
Changed the handling of default p2p port. Previously, a fixed port was being used which was not serving the purpose when the operator runs a node and specifies a non-standard local port. The revised code implements variable 'desired_external_port' to set the port number from the normalized peer-to-peer listening address. This allows the use of a non-standard public address. This change makes the system more adaptable to operator wishes and avoids potential conflicts.
=> Refactor p2p port handling

components/addressmanager/src/lib.rs
two lines to make the `test_network_distribution_weighting` test harder to randomly fail.
=> Harden `test_network_distribution_weighting` test.

consensus/src/processes/pruning_proof/mod.rs
The following line of logic in [kaspad-go](https://github.com/kaspanet/kaspad/blob/master/domain/consensus/processes/pruningproofmanager/pruningproofmanager.go#L199) was missing from rust impl. This means that we were searching for common ancestor when not needed hence loosing contiguous topology guarantees known from proof validation or from ongoing relation maintenance. This in turn lead to not including `block_at_depth_2m` in the proof in some cases, thus deleting it prematurely
=> Build pruning proof -- Bug fix

mining/src/manager.rs, mining/src/manager_tests.rs, mining/src/mempool/mod.rs, mining/src/model/mod.rs, mining/src/model/tx_query.rs, protocol/flows/src/v5/txrelay/flow.rs, rpc/core/src/error.rs, rpc/service/src/service.rs
Refactor mempool tx query to an enum instead of 2 booleans. This makes it impossible to make an inconsistent query (previously managed by internal mempool assertions). Fixes an rpc crash bug
=> RPC mempool transaction query -- Bug fix

consensus/src/consensus/factory.rs, kaspad/src/daemon.rs
This detects if the current Genesis (as defined in code) is in the local active consensus DB - which it always should be. If it isn't, then the network has restarted and the local DB must be deleted. Only applied to non-mainnet networks as mainnet is never retarted.
=> Request DB reset when dev/test/sim network restart is detected

Cargo.lock, Cargo.toml, utils/Cargo.toml, utils/src/lib.rs, utils/src/request_response_size_middlewares.rs
Introduced a new module `request_response_size_middlewares` to utils library to count the sizes of request and response bodies. Furthermore, added several dependencies to Cargo.toml and updated Cargo.lock necessary for new functionality. This includes libraries like 'hyper', 'tower', and 'pin-project-lite'. The new implementation will provide us with exact sizes of data transferred.
=> Add request/response size middlewares and dependencies

kaspad/src/daemon.rs
Trying to set FD limit higher than 8k on windows causes the application to crash. Reducing the value accordingly.
=> Reduce desired daemon soft FD limit to 8k for Windows compatibility

Cargo.lock, Cargo.toml, kaspad/src/args.rs, kaspad/src/daemon.rs, protocol/flows/src/flow_context.rs, protocol/flows/src/flowcontext/orphans.rs, protocol/flows/src/v5/blockrelay/flow.rs, protocol/flows/src/v5/ibd/flow.rs
Includes 3 major components which can be reviewed separately:
1. Complete a full "revalidate orphans" algorithm including unorphaning (to be run post IBD)
2. Close the sync gap between consensus and the block orphan pool leading to stuck orphans
3. Add an IBD-related heuristic for deciding if to keep orphans  
The end result tested via an internal TN11 testnet shows that with all the above, on-going P2P block exchange is smooth also on a 10BPS network and between peers with RTT > block time (=100ms)
=> Tighten up P2P relay and orphan management in order to perfect high-BPS block exchange

Cargo.lock, Cargo.toml, kaspad/Cargo.toml, kaspad/src/main.rs, simpa/Cargo.toml, simpa/src/main.rs, testing/integration/Cargo.toml, testing/integration/src/consensus_integration_tests.rs, testing/integration/src/consensus_pipeline_tests.rs, testing/integration/src/daemon_integration_tests.rs, testing/integration/src/lib.rs, utils/alloc/Cargo.toml, utils/alloc/src/lib.rs
Since rusty-kaspa uses a lot of allocations, the RSS remains high even after the memory is free. This should be mitigated by using mimalloc which utilizes the use of MADV_FREE and MADV_DONTNEED (and equivalent techniques on non unix-like systems) which tend to release memory earlier and help in keeping the RSS small.
=> Move to mimalloc

components/connectionmanager/src/lib.rs, consensus/core/src/errors/pruning.rs, consensus/src/consensus/mod.rs, consensus/src/consensus/services.rs, consensus/src/pipeline/pruning_processor/processor.rs, consensus/src/processes/pruning_proof/mod.rs, kaspad/src/args.rs, kaspad/src/daemon.rs, metrics/perf_monitor/src/counters.rs, protocol/flows/src/v5/ibd/flow.rs, protocol/p2p/src/core/connection_handler.rs, simpa/src/main.rs
Adds some missing logs and is meant to be an aggregated PR for other minor convenient additions. Please open a PR over this branch if you wish to add anything. All changes should be small in scope.
Some suggestions to add here:
1. Add to `Consensus` an atomic boolean set at `Consensus::signal_exit` which can be used by processors such as the pruning processor to exit long operations early if the app is shutting down. Another place to use this flag is `PruningProofManager::validate_pruning_point_proof`. 
2. Add `--norpc` flag support to `kaspad` cmd options
3. Metrics logs: split `perf-monitor` metrics log to two more readable and short lines. Consider printing numbers also in readable format with units such as KB,MB,GB. Change cmd option `perf_metrics_interval_sec` default value to 10. ** …
=> Adds missing logs and other minor convenient additions 

components/addressmanager/src/stores/address_store.rs, components/addressmanager/src/stores/banned_address_store.rs, consensus/core/src/blockstatus.rs, consensus/core/src/config/mod.rs, consensus/core/src/errors/config.rs, consensus/core/src/tx.rs, consensus/src/consensus/factory.rs, consensus/src/consensus/storage.rs, consensus/src/model/stores/acceptance_data.rs, consensus/src/model/stores/block_transactions.rs, consensus/src/model/stores/block_window_cache.rs, consensus/src/model/stores/depth.rs, consensus/src/model/stores/ghostdag.rs, consensus/src/model/stores/headers.rs, consensus/src/model/stores/reachability.rs, consensus/src/pipeline/monitor.rs, crypto/hashes/src/lib.rs, indexes/core/src/indexed_utxos.rs, kaspad/src/args.rs, kaspad/src/daemon.rs, metrics/perf_monitor/src/lib.rs, mining/src/manager.rs, mining/src/mempool/config.rs, protocol/flows/src/flow_context.rs, protocol/flows/src/v5/blockrelay/flow.rs, simpa/src/main.rs, utils/src/mem_size.rs
- Adds a RAM usage scale factor configurable from the command line. The scale factor is applied to memory allocation bounds. Nodes with limited RAM (~4-8GB) should set this to ~0.3-0.5 respectively. Nodes with a large RAM (~64GB) can set this value to ~3.0-4.0 and gain superior performance especially for syncing peers faster on high-BPS networks
- Changes block txs and acceptance data stores to use tracked bytes mode
- Reduces orphan block log flood (appears in some cases on start-up)
- Benchmarks using simpa show that normal operation remains performant also if setting `--ram-scale=0.3` (but below that perf starts degrading)
=> Add a RAM usage scale factor configurable from the command line

Cargo.lock, mining/src/manager.rs, protocol/flows/src/flow_context.rs, protocol/flows/src/flowcontext/transactions.rs, protocol/flows/src/v5/txrelay/flow.rs, protocol/p2p/Cargo.toml, protocol/p2p/src/core/hub.rs
When P2P load is high:
1. Limit the number of peers to broadcast to
2. Limit the number of transactions requested when requesting missing transactions
3. Reduce the size of the invs channel and allow dropping invs when it's full
=> Implement basic tx throttling on high P2P load

kaspad/src/args.rs, kaspad/src/daemon.rs
- Add nogrpc flag: When set, the gRPC service is not initialized
- Set default grpc listen to 127.0.0.1
=> Implement "nogrpc" flag and change default rpc listen ip

wallet/core/src/imports.rs, wallet/core/src/storage/transaction/record.rs, wallet/core/src/utxo/context.rs, wallet/core/src/utxo/pending.rs, wallet/core/src/utxo/processor.rs, wallet/core/src/utxo/reference.rs, wallet/core/src/utxo/scan.rs, wallet/core/src/utxo/settings.rs, wallet/core/src/utxo/test.rs
Convert wallet network settings to global consts introducing `NetworkParams` in the wallet framework similar to consensus `Params`.  For now this contains confirmation periods but is also intended to be used to statically configure various options for txgen per-network fee processing.
=> Convert settings to global consts and fix TN11 conbase maturity times

rpc/wrpc/client/src/client.rs, rpc/wrpc/server/src/server.rs
Do not inject port based on network type in wRPC URL when using SSL or the URL has a path.
Current behavior always injects port unless explicitly specified, which creates interference when using WebSocket proxies (that use URL paths) requiring us to always specify ports `443` or `80`.
=> Update port handling in wRPC URL parser

Cargo.toml, utils/alloc/Cargo.toml
The `override` mimalloc feature causes instability in macos builds
=> Remove mimalloc override feature for macos

utils/src/sync/rwlock.rs, utils/src/sync/semaphore.rs
Readers-Preferred RwLock (aka pruning lock): Increase the semaphore yield duration to 30 micros + tighten the test (so that w/o this fix it would fail with certainty)
=> Fix yield duration of readers-preferred rwlock

wallet/core/src/account/mod.rs, wallet/core/src/lib.rs, wasm/README.md, wasm/src/lib.rs, wasm/src/utils.rs
Mostly small README changes and updated links for external guides.
=> Misc doc updates

README.md, kaspad/Cargo.toml, kaspad/src/args.rs, rpc/wrpc/server/src/address.rs
=> allow using a toml config file

Cargo.lock, kaspad/src/args.rs
With the change from #429 the defaults are now used whenever no value is passed to cli args.
appdir default value used to not matter, but now if it's set to `Some("datadir")` it makes the datadir be inside the current directory - as opposed to the original behavior of it being in `~/.rusty-kaspa`
=> Set the default Args appdir to None

Cargo.lock, Cargo.toml, consensus/core/src/constants.rs, consensus/core/src/tx.rs, consensus/src/consensus/mod.rs, consensus/src/pipeline/virtual_processor/utxo_validation.rs, consensus/src/processes/mass.rs, consensus/src/processes/transaction_validator/transaction_validator_populated.rs, mining/src/mempool/validate_and_insert_transaction.rs, protocol/flows/src/v5/txrelay/flow.rs, simpa/src/simulator/miner.rs
As [suggested](https://github.com/kaspanet/kips/blob/master/kip-0009.md#current-status) by KIP9, this PR updates mass calculations to reflect the final proposal wherever possible. This includes:
- Applying a maximum over `stoarge_mass` and `compute_mass` rather than summing them
- Using the relaxed formula for the cases ` |O| = 1 OR |O| <= |I| <= 2`
The updates are applied on mainnet and TN10 on the mempool level. TN11 requires a hard-fork for this update and remains unchanged for now also on the mempool level (since the new rules are more permissive)
=> Implement updated KIP9 mempool rules (excluding TN11)

consensus/src/pipeline/header_processor/processor.rs, consensus/src/pipeline/virtual_processor/utxo_validation.rs, consensus/src/processes/mass.rs, consensus/src/processes/pruning_proof/mod.rs, kaspad/src/args.rs, notify/src/address/tracker.rs, notify/src/listener.rs, notify/src/notifier.rs
The following describes the pruning bug and the fix assuming sufficient prior knowledge. 
Some notation: 
- High levels: block levels at which there are less than 2000 blocks since genesis (so genesis is part of that proof level). Currently this is approx around level 39 and above. 
- Low levels: block levels close to current difficulty and hence it is likely that all 2000 proof blocks are within the last day before the corresponding pruning point.
- Intermediate levels: block levels which are not that rare but are still unlikely to have more than 2000 blocks all within a single day. Hence their level proof likely has blocks **both** before and after the previous pruning point.
The bug is mostly in the case of intermediate levels. It requires that such a block is mined in the anticone of …
=> Fix for the pruning proof rebuild issue (issue #444)

components/consensusmanager/src/session.rs, consensus/src/processes/pruning_proof/mod.rs, protocol/flows/src/v5/ibd/flow.rs
Initialize the pruning point depth store for the rare case where the pruning point is the first sink during initial IBD (virtual processor calls the depth store for each new sink)
=> Initialize pruning point depth store -- minor bug fix

Cargo.toml, cli/Cargo.toml, components/addressmanager/src/stores/address_store.rs, consensus/core/Cargo.toml, consensus/core/src/sign.rs, consensus/wasm/Cargo.toml, crypto/txscript/src/data_stack.rs, crypto/txscript/src/opcodes/mod.rs, kaspad/src/args.rs, kos/src/metrics/ipc.rs, mining/src/mempool/model/pool.rs, rpc/core/Cargo.toml, rpc/core/src/model/address.rs, rpc/wrpc/client/src/client.rs, rpc/wrpc/client/src/parse.rs, utils/benches/bench.rs, wallet/core/Cargo.toml, wallet/core/src/storage/local/collection.rs, wallet/core/src/tx/generator/test.rs, wallet/core/src/utxo/processor.rs
Changes required for Rust 1.78 compatibility.
=> Rust 1.78 compatibility

kaspad/src/args.rs, rpc/wrpc/server/src/address.rs, utils/src/networking.rs
Adds support for IP only for the --rpclisten-borsh/json flags.
If a port is not provided a default port for a given network would be used.
=> Add support for IP only for --rpclisten-borsh/json (#402)

protocol/p2p/src/common.rs
Until this rare issue is resolved, displays a message to hint a user would need to reset the database when the P2P reject reason "block not found" persists after IBD.
=> Add hint message for P2P reject reason block not found.

consensus/core/src/api/mod.rs, consensus/core/src/block.rs, consensus/core/src/config/genesis.rs, consensus/core/src/errors/tx.rs, consensus/core/src/header.rs, consensus/core/src/merkle.rs, consensus/core/src/subnets.rs, consensus/core/src/tx.rs, consensus/src/consensus/mod.rs, consensus/src/consensus/test_consensus.rs, consensus/src/model/stores/headers.rs, consensus/src/pipeline/body_processor/body_validation_in_context.rs, consensus/src/pipeline/body_processor/body_validation_in_isolation.rs, consensus/src/pipeline/virtual_processor/processor.rs, consensus/src/processes/transaction_validator/tx_validation_in_isolation.rs, mining/src/block_template/builder.rs, mining/src/testutils/consensus_mock.rs, protocol/flows/src/flowcontext/orphans.rs
Fixes a TN11 bug where transaction mass field hashing was not activated when modifying a cached block template. 
This produced invalid blocks when two miners with different addresses were connected to the same node, frequently triggering this code path and resulting in many bad Merkle root blocks
=> TN11 bug fix: activate mass hashing when modifying a cached block template  

consensus/src/model/services/reachability.rs, consensus/src/pipeline/pruning_processor/processor.rs, consensus/src/processes/parents_builder.rs, consensus/src/processes/reachability/tests/mod.rs, utils/src/sync/semaphore.rs
1. In `ParentsBuilder` optimize the execution path of the common case for high levels
2. Prune relations for all levels below the affiliated proof level for block
3. Keep relations for multi-level parents of pruning point and its anticone  
(each item is in its own commit, by order)
=> A few optimizations related to multi-level relations

consensus/core/src/tx.rs, mining/errors/src/mempool.rs, mining/src/manager.rs, mining/src/manager_tests.rs, mining/src/mempool/config.rs, mining/src/mempool/mod.rs, mining/src/mempool/model/frontier.rs, mining/src/mempool/model/transactions_pool.rs, mining/src/mempool/model/tx.rs, mining/src/mempool/validate_and_insert_transaction.rs, mining/src/testutils/consensus_mock.rs
This PR:
* Increases mempool expiry time to 24h
* Increases orphan tx limit to 500
* Adds a compute-mass limit to the mempool (as a proxy to mempool memory size) and changing the eviction mechanism to prefer transactions with lower fee rate.
=> Mempool tweaks

mining/src/manager.rs, mining/src/mempool/mod.rs, mining/src/mempool/model/orphan_pool.rs, mining/src/mempool/model/pool.rs, mining/src/mempool/model/transactions_pool.rs
**_Problem_**: when revalidating high priority txs, the revalidated tx was updated within the inner tx pool.  If the revalidation resulted in missing inputs, this update would result in a change in the size of the updated tx which wasn't tracked by `transaction_pool.estimated_size`. The first 2 commits in this PR contain 2 orthogonal fixes to this problem, which are both correct independently. 
**_Fix 1_**: remove crate level mut access to inner tx structure, and perform correct byte tracking whenever the inner collection is accessed.
**_Fix 2_**: in `revalidate_high_priority_transactions`, update the revalidated tx only if it validated correctly, otherwise we remove it anyway so there's no need to update. Technically, this fixes the problem as well, since fully populated txs never change …
=> Transaction pool -- fix rare cases where byte size tracking was inaccurate

rpc/core/src/model/message.rs, rpc/core/src/model/tests.rs, rpc/grpc/core/proto/rpc.proto, rpc/grpc/core/src/convert/message.rs, rpc/service/src/service.rs, utils/src/sysinfo.rs
This PR adds an optional socket limit obtained from the system nginx.conf (if present).  This information is helpful in detecting optional limits imposed on wRPC connections if they are proxied locally using NGINX.
=> Add optional proxy socket limit info to utils::SystemInfo()

.github/workflows/deploy.yaml, consensus/core/src/utxo/utxo_diff.rs, consensus/src/consensus/storage.rs, consensus/src/model/stores/acceptance_data.rs, consensus/src/model/stores/block_transactions.rs, consensus/src/model/stores/ghostdag.rs, consensus/src/model/stores/headers.rs, consensus/src/model/stores/mod.rs, consensus/src/model/stores/utxo_set.rs, consensus/src/pipeline/body_processor/body_validation_in_context.rs, consensus/src/processes/coinbase.rs, consensus/src/processes/pruning.rs, consensus/src/processes/sync/mod.rs, crypto/muhash/fuzz/fuzz_targets/u3072.rs, crypto/muhash/src/u3072.rs, crypto/txscript/src/caches.rs, crypto/txscript/src/data_stack.rs, crypto/txscript/src/opcodes/mod.rs, database/src/registry.rs, indexes/utxoindex/src/stores/indexed_utxos.rs, math/src/uint.rs, mining/src/testutils/coinbase_mock.rs, protocol/flows/src/flowcontext/orphans.rs, protocol/p2p/src/convert/net_address.rs, utils/src/mem_size.rs, utils/src/option.rs
Change directory back to repo root after building toolchain.
=> Change directory back to repo root.

Cargo.toml, consensus/client/src/utxo.rs, rpc/core/src/wasm/convert.rs, rpc/core/src/wasm/message.rs, wallet/core/src/tx/generator/generator.rs, wallet/core/src/tx/generator/test.rs, wallet/core/src/wasm/tx/mass.rs, wallet/keys/src/publickey.rs
This PR contains various WASM SDK improvements based on community feedback:
- Introduces `maximumStandardTransactionMass()`
- Fixes documentation for `calculateTransactionMass()`
- Adds `PublicKey::fingerprint()`
Addresses the following critical issues:
- Fixes an issue in `submitTransaction()` causing a "recursive mutex use" error
The latest WASM SDK builds containing these updates can be found at: https://kaspa.aspectron.org/nightly/downloads/
=> WIP: Updates for 15-rc3

Cargo.lock, metrics/core/src/data.rs, metrics/core/src/lib.rs, wallet/core/src/imports.rs, wallet/core/src/utxo/context.rs, wallet/core/src/utxo/processor.rs, wallet/core/src/utxo/scan.rs
- Fix an issue in the metrics client that results in the first metrics snapshot having invalid values (by skipping first snapshot).
- Fix `extend_from_scan()` functionality of the `UtxoContext` resulting in long processing times for UTXO sets containing more than 500k UTXOs.
=> 15 rc4 updates

rpc/core/src/wasm/message.rs
Plural is used for these two fields https://github.com/kaspanet/rusty-kaspa/blob/f335376be8d720f709f04f3d12fe27a5dea5535f/rpc/core/src/wasm/message.rs#L1602-L1603
=> Fix WASM interface typo for `normalBuckets` and `lowBuckets` in `IFeerateBucket`

wallet/bip32/src/mnemonic/mod.rs, wallet/bip32/src/mnemonic/phrase.rs, wallet/bip32/src/mnemonic/seed.rs
Kaspa fork of the `bip32` crate inherited a `bip39` feature which has been removed as `bip39` (mnemonic handling) is an integral part of the `kaspa-bip32` crate.  However, a left-over `cfg_attr()` gate was not noticed as it was specific for `docs.rs` resulting in docs.rs build failure.  This PR cleans this up.
=> Cleanup legacy bip39 cfg flags interfering with docs.rs documentation builds

consensus/src/consensus/mod.rs, consensus/src/pipeline/virtual_processor/processor.rs, consensus/src/pipeline/virtual_processor/utxo_validation.rs
Parallelize parts of the muhash calculations (`add_utxo` and `add_transaction`) then later combine results so we can delegate the heavier work to multiple threads.
=> Parallelize MuHash calculations

consensus/core/src/api/mod.rs, consensus/core/src/errors/pruning.rs, consensus/core/src/lib.rs, consensus/core/src/pruning.rs, consensus/pow/src/lib.rs, consensus/src/consensus/mod.rs, consensus/src/consensus/services.rs, consensus/src/pipeline/header_processor/pre_ghostdag_validation.rs, consensus/src/processes/difficulty.rs, consensus/src/processes/ghostdag/protocol.rs, consensus/src/processes/pruning_proof/apply.rs, consensus/src/processes/pruning_proof/build.rs, consensus/src/processes/pruning_proof/validate.rs, math/src/uint.rs, protocol/flows/src/v5/ibd/flow.rs
- On validating pruning proof, check pow to ensure level blocks have valid work
- Standardize level work - set a minimum amount of work per level to create a more uniform comparable blue work at higher levels
- Better pruning proof comparison between current consensus and syncer's proof
=> Pruning proof minor improvements

crypto/txscript/src/data_stack.rs, crypto/txscript/src/lib.rs, crypto/txscript/src/opcodes/mod.rs, crypto/txscript/src/script_builder.rs
Unifying `OpcodeData<i32/i64/Kip10I64>` to use `SizedEncodeInt` for serialization.
Critical lines and explanation:
1. https://github.com/someone235/rusty-kaspa/blob/976313f0f4c492061689d84811b17ee1ea73cc8b/crypto/txscript/src/data_stack.rs#L178
Here we limit any `push_item<i32>` to 4 bytes. This is fine since we nowhere use this method.
2. https://github.com/someone235/rusty-kaspa/blob/976313f0f4c492061689d84811b17ee1ea73cc8b/crypto/txscript/src/data_stack.rs#L166
Here we limit any `push_item<i64>` to 8 bytes. Explanation for safety is in the code.
3. https://github.com/someone235/rusty-kaspa/blob/976313f0f4c492061689d84811b17ee1ea73cc8b/crypto/txscript/src/data_stack.rs#L173
Here we limit any `pop_items<i32>` to 4 bytes, disallowing the use of `i32::MIN`. This is fine since in any place …
=> Some simplification to script number types

consensus/core/src/hashing/sighash.rs, simpa/Cargo.toml
Addressing https://github.com/kaspanet/rusty-kaspa/pull/591#pullrequestreview-2467331100
=> Small fixes related to enabling payload

rothschild/src/main.rs
Rust panic due to  SystemTime after running Rotschild for hours.
Changed functions to use std::time::Instant which is monotonic, to avoid Rust panics with SystemTime, per recommendation of @143672 in discord.
Replaced some unwraps with an expect.
Removed redundant brackets, and secp256k1::
Tested working on Ubuntu 22.04 LTS, compiled with 'cargo build --release'
Ran for 3 hours without problems.
Note that I am a newbie Rust dev.
=> Instant time instead of SystemTime

consensus/benches/check_scripts.rs, consensus/core/src/config/params.rs, consensus/src/consensus/services.rs, consensus/src/processes/transaction_validator/mod.rs, consensus/src/processes/transaction_validator/tx_validation_in_utxo_context.rs, crypto/txscript/errors/src/lib.rs, crypto/txscript/examples/kip-10.rs, crypto/txscript/src/lib.rs, crypto/txscript/src/opcodes/mod.rs, crypto/txscript/src/runtime_sig_op_counter.rs, crypto/txscript/src/standard/multisig.rs, mining/src/mempool/check_transaction_standard.rs, testing/integration/src/consensus_integration_tests.rs, wallet/pskt/src/pskt.rs
Changes signature operation counting from static analysis to runtime counting during script execution for improved accuracy.
- Add sig_op tracking fields to TxScriptEngine
- Remove static sig_op counting functions
- Count sig_ops during script execution 
- Add runtime checks for sig_op limits
- Add new error type for sig_op limit violations
- Update transaction validation to use runtime counting
- Changes sig_op validation timing from pre-execution to during execution
- May affect transaction fee estimation
Requires manual testing and careful review of sig_op counting logic.
=> calculate sig ops on fly

Cargo.lock, Cargo.toml, indexes/utxoindex/src/index.rs, indexes/utxoindex/src/stores/store_manager.rs, indexes/utxoindex/src/stores/supply.rs, indexes/utxoindex/src/update_container.rs
The circulating supply value is tracked as a single DB entry within the UTXO index store (external to consensus). 
This value was not tracked properly when mergeset fees exceeded new block rewards, resulting in an accumulating error to the tracked value. Note that the actual sum of supply in the UTXO set is always accurate.  
This PR fixes the tracked store value to always be updated with the exact delta also when negative, and still provides a monotonic RPC value by keeping a separate monotonic runtime value.
=> Proper tracking of the accumulative circulating supply store value

consensus/client/src/utxo.rs, consensus/core/src/mass/mod.rs, consensus/core/src/tx.rs, consensus/core/src/tx/script_public_key.rs, wallet/core/src/tx/mass.rs
Generalizes KIP9 to handle the case where the UTXO script public key is larger than standard keys (max 33 bytes for ECDSA) and thus captures more (persistent) storage.
The idea is based on the following simple reduction:
- Define the base UTXO storage unit (`UTXO_UNIT=100` bytes seems a natural choice)
- For a UTXO entry, let `P := ceiling(entry.size/UTXO_UNIT)` denote the UTXO's "plurality"
- Treat the entry as `P` entries each holding `entry.amount/P` KAS value 
This directly maps the usage of such a big entry to the usage of `P` single-unit entries in a model where all entries have the same size.
The choice of `UTXO_UNIT=100` is driven by the const parts of the UTXO = 63 bytes + max standard public key which is 33 bytes.
Implementing the above reduction in the storage mass calculation …
=> Generalized KIP9--storage mass plurality (Crescendo)

consensus/src/processes/pruning_proof/build.rs
Improves proof size per level especially when DAG level drops significantly like it does in testnet. This services as a simpler fix for the short-term that allows us to improve on the proof sizes already. https://github.com/kaspanet/rusty-kaspa/pull/627 should still be reviewed and merged post Crescendo.
See the attached image for a comparison in latest TN10 where a GPU came on the net (left side is new result from this PR)
=> Start the pruning proof per level search at the lowest required depth

Cargo.lock, Cargo.toml, consensus/src/processes/pruning_proof/build.rs, consensus/src/processes/pruning_proof/mod.rs, consensus/src/processes/pruning_proof/validate.rs, kaspad/src/daemon.rs, protocol/flows/src/service.rs, protocol/flows/src/v5/ibd/flow.rs, protocol/p2p/src/convert/messages.rs, protocol/p2p/src/core/hub.rs
Optimizes memory usage of the cached pruning proof, by reusing existing Arcs and making sure each header is held in memory only once.
Additional minor additions:
1. Switch some irrelevant logs to debug
2. Disable p2p server if `--connect` is used or if `--maxinpeers=0`
3. Log inbound and outbound connection counts 
4. Fix a leftover edge case from multilevel GD upgrade
5. Bumps the version so that the memory usage patterns can be affiliated with the version
=> Crescendo-related RAM optimizations & miscellaneous  

components/consensusmanager/src/session.rs, consensus/core/src/api/mod.rs, consensus/core/src/config/mod.rs, consensus/src/consensus/mod.rs, consensus/src/model/stores/pruning.rs, consensus/src/pipeline/pruning_processor/processor.rs, consensus/src/pipeline/virtual_processor/processor.rs, consensus/src/pipeline/virtual_processor/utxo_inquirer.rs, consensus/src/processes/pruning_proof/mod.rs, database/src/registry.rs, docs/testnet10-transition.md, kaspad/src/args.rs, kaspad/src/daemon.rs
- New configuration usage `--retention-period-days=N` - set this to some number to keep that many days of data. If this is smaller than the pruning period duration, a pruning period duration amount of data will be kept still.
- Implementation detail - this goes through the selected parent chain to find the first block that is past the N days threshold. There is no extra logic that ensures the anticone of the last SPC block found is also retained as such those will still be pruned.
=> Implement Retention Period Support

consensus/src/pipeline/pruning_processor/processor.rs, consensus/src/pipeline/virtual_processor/utxo_inquirer.rs, simpa/src/main.rs
Index data needs to retain data up to retention period root for calls that require the index of it (such as get_utxo_return_address) to work.
Additional changes:
- adds support for retention_period_days in simpa
- sink timestamp is used as `now` for retention period time calculations
Testing with retention:
```
cargo run --release --bin simpa -- -n=6000 -t=1 --test-pruning --loglevel=info --retention-period-days=0.01
```
Testing original case:
```
cargo run --release --bin simpa -- -n=6000 -t=1 --test-pruning --loglevel=info
```
=> Retain index data up to retention period root

protocol/flows/src/flow_context.rs
Currently, new nodes don't know that Crescendo has already been activated, so they sometimes try to sync from old nodes, and their IBD fails when they reach the Crescendo daa score
=> Make mainnet nodes always disconnect p2p v6 nodes
