kaspanet/rusty-kaspa

consensus/core/src/hashing/header.rs
consensus/core/src/hashing/mod.rs
consensus/core/src/hashing/tx.rs
consensus/core/src/header.rs
consensus/core/src/lib.rs
consensus/core/src/subnets.rs
consensus/core/src/tx.rs
consensus/core/src/utxo.rs

Still wip, but being merged to allow dependent code to be written in parallel

UTXO Model -- Part 1 (tx + tx hashing)

---

Cargo.lock
Cargo.toml
p2p/Cargo.toml
p2p/build.rs
p2p/proto/messages.proto
p2p/proto/p2p.proto
p2p/proto/rpc.proto
p2p/scripts/wget_kaspad_protobufs.sh
p2p/src/bin/p2p_client.rs
p2p/src/bin/p2p_server.rs
p2p/src/kaspa_flows.rs
p2p/src/kaspa_grpc.rs
p2p/src/kaspa_p2p.rs
p2p/src/lib.rs

1. Server + Client side
2. Basic flow example
ToDo:
1. Refine Flows API 
2. Configuration usage for general channel-size

P2P layer for rusty-kaspa

---

crypto/txscript/errors/src/lib.rs
crypto/txscript/src/lib.rs

Fixed one of the todos mentions in https://github.com/kaspanet/rusty-kaspa/issues/122

Added check we're outside conditions in the end of script

---

consensus/src/pipeline/virtual_processor/processor.rs

When the number of tips gets higher than half of the maximum parents a block can reference, this new algorithm ensure that concurrently mining nodes will build blocks connecting different sets of parents, thus improving the overall connectivity between blocks.

Enhance broad DAG block interconnections 

---

consensus/core/src/config/bps.rs
consensus/core/src/config/constants.rs
mining/src/manager_tests.rs
rothschild/src/main.rs

Finalizes consensus constants for testnet 11

Testnet-11 final adjustments

---

consensus/core/src/config/params.rs
consensus/src/model/stores/relations.rs
consensus/src/pipeline/pruning_processor/processor.rs
consensus/src/processes/relations.rs
mining/src/block_template/selector.rs
mining/src/mempool/model/pool.rs
mining/src/model/topological_index.rs

Add an additional mainnet DNS-seeder, maintained by yours truly. As discussed with Michael Sutton.

Added a mainnet dnsseeder

---

Cargo.lock
components/addressmanager/src/lib.rs
consensus/src/consensus/factory.rs
consensus/src/consensus/test_consensus.rs
consensus/src/processes/pruning_proof/mod.rs
consensus/src/processes/reachability/inquirer.rs
consensus/src/processes/relations.rs
database/Cargo.toml
database/src/db.rs
database/src/db/conn_builder.rs
database/src/lib.rs
database/src/utils.rs
indexes/processor/src/processor.rs
indexes/utxoindex/src/index.rs
kaspad/src/main.rs
simpa/src/main.rs
simpa/src/simulator/network.rs
testing/integration/src/integration_tests.rs

implement rocksdb connect builder that  allows to set different settings

Rocksdb config

---

rpc/core/src/convert/notification.rs
rpc/core/src/convert/tx.rs

missing: rpc integration test for this case

RPC notifications -- add missing acceptance data

---

consensus/src/consensus/mod.rs
consensus/src/pipeline/pruning_processor/processor.rs

Fixes a bug where proof headers get a status during the first prune operation even though they never got a status when the node synced for the first time. This lead to an RPC vulnerability since they had a valid status but were missing other kinds of data

Pruning processor -- set status only if previously set

---

crypto/txscript/src/standard.rs
crypto/txscript/src/standard/multisig.rs

adds functionality to create multisig redeem script.
adds tests related to it

Feat multisig

---

Cargo.lock
Cargo.toml
consensus/core/src/network.rs
consensus/src/consensus/storage.rs
kaspad/src/daemon.rs
mining/errors/src/mempool.rs
mining/src/manager.rs
mining/src/mempool/config.rs
mining/src/mempool/validate_and_insert_transaction.rs
protocol/flows/src/v5/txrelay/flow.rs
rpc/grpc/server/Cargo.toml
rpc/grpc/server/src/connection.rs
rpc/grpc/server/src/manager.rs

For context see https://github.com/kaspanet/kaspad/pull/2223
Also fixes GRPC server to allow multiple GRPC clients from the same IP+PORT

Apply mempool dust prevention patch + version prep

---

metrics/perf_monitor/src/lib.rs

Added a warning message in case the new IO read or write bytes values are less than the previous values. This was done using the unwrap_or_else() function to prevent the program from potentially crashing when the subtraction operation results in a negative value.

Add warning for negative IO delta values

---

components/addressmanager/src/lib.rs
components/addressmanager/src/port_mapping_extender.rs
consensus/src/consensus/mod.rs
consensus/src/pipeline/virtual_processor/processor.rs
consensus/src/pipeline/virtual_processor/utxo_validation.rs
consensus/src/processes/transaction_validator/transaction_validator_populated.rs
rpc/grpc/core/src/convert/header.rs
testing/integration/src/common/daemon.rs
testing/integration/src/daemon_integration_tests.rs
testing/integration/src/mempool_benchmarks.rs

1. optimize virtual processing and its interference with prune lock (designed to avoid pruning starvation on 10BPS)
2. BBT: validate transactions in parallel
3. Skip redundant validation of selected parent transactions

Some virtual processor optimizations

---

cli/Cargo.toml
kos/Cargo.toml
metrics/perf_monitor/Cargo.toml
mining/errors/Cargo.toml

Minor updates that are required for crate publishing on crates.io

Updates required for crate publishing

---

README.md

remove the space to escape the newline instead.

make step 3. of linux installation not fail copy and paste

---

wallet/core/src/account/variants/bip32.rs
wallet/core/src/storage/local/interface.rs
wallet/core/src/storage/local/transaction/fsio.rs
wallet/core/src/utxo/context.rs
wallet/core/src/wallet/mod.rs

This PR contains fixes for bugs/issues that were identified during the last testing phase.

Minor wallet framework updates

---

Cargo.lock
Cargo.toml
consensus/src/pipeline/header_processor/pre_ghostdag_validation.rs

Note that the change does not affect 1bps settings where target block time =1000

Fix timestamp deviation tolerance for 10 bps 

---

protocol/flows/src/v5/txrelay/flow.rs

Fixes https://discord.com/channels/599153230659846165/917551031259377664/1193796441248911430

Fix sub overflow panic on txrelay flow time check

---

wallet/core/src/storage/local/transaction/indexdb.rs

Temporary implementation for `get_range()` (this is a part of the pending overhaul and implementation for the wallet transaction history API).

Updates to indexdb transaction storage functionality

---

Cargo.lock
Cargo.toml
wallet/core/Cargo.toml
wallet/core/src/wallet/mod.rs

feat: import golang-based wallet account

---

mining/src/model/topological_index.rs
rothschild/src/main.rs
rpc/grpc/core/src/convert/header.rs
testing/integration/src/common/utils.rs

fix lints.

---

.github/workflows/ci.yaml

Address GitHub Actions warnings re Node 20

---

mining/src/mempool/model/frontier.rs

The feerate estimator deals with outliers (extreme high feerate transactions which highly deviate from the average) by considering them as if they capture block space, and then estimating the feerate required for being included in the remaining block space. See 
the [python notebook](https://github.com/kaspanet/rusty-kaspa/blob/dev/mining/src/feerate/fee_estimation.ipynb) for full details. 
Up until now, the captured block space for each outlier was the _average_ tx mass. However this is inaccurate if the outliers happen to have mass << average mass. In which case they capture too much of the block space and the predicted feerate estimations turn out to be much higher than needed. 
In this PR we fix this by capturing block space by the specific mass of the outlier transaction. The PR also …

Feerate estimator outliers: capture block slot by the specific mass of the outlier transaction

---

wallet/pskt/src/utils.rs

fix wrong combiner condition

---

rpc/wrpc/server/src/connection.rs

This PR fixes data format in wRPC JSON notification messages

fix wRPC JSON notification message format

---

Cargo.lock
Cargo.toml

Version bump for stable release

Bump version to 0.16.0

---

metrics/core/src/lib.rs
mining/benches/bench.rs
notify/benches/bench.rs
notify/src/error.rs
protocol/mining/src/rule_engine.rs
rpc/grpc/client/src/error.rs
rpc/grpc/server/src/request_handler/method.rs

paranthesis lints
